# Generated by Django 6.0.1 on 2026-02-07 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0003_alter_department_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_created', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organization.department')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('PROJECT_MANAGER', 'Project Manager'), ('TECH_LEAD', 'Tech Lead'), ('PRODUCT_OWNER', 'Product Owner'), ('SOFTWARE_ENGINEER', 'Software Engineer'), ('BACKEND_ENGINEER', 'Backend Engineer'), ('FRONTEND_ENGINEER', 'Frontend Engineer'), ('DATA_ENGINEER', 'Data Engineer'), ('ML_ENGINEER', 'ML Engineer'), ('DEVOPS_ENGINEER', 'DevOps Engineer'), ('QA_ENGINEER', 'QA Engineer'), ('QA_LEAD', 'QA Lead'), ('SECURITY_ENGINEER', 'Security Engineer'), ('UI_UX_DESIGNER', 'UI/UX Designer'), ('BUSINESS_ANALYST', 'Business Analyst'), ('SYSTEM_ADMIN', 'System Administrator'), ('SUPPORT_ENGINEER', 'Support Engineer'), ('INTERN', 'Intern'), ('CONSULTANT', 'Consultant')], max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='work.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='work_projec_code_724924_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='work_projec_status_98c5e8_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['project'], name='active_assignment_per_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(condition=models.Q(('is_active', True)), fields=['user'], name='active_assignment_per_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('project', 'user'), name='unique_active_assignment_per_user_per_project'),
        ),
    ]
