# Generated by Django 6.0.1 on 2026-02-08 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='unassigned_at',
        ),
    ]
